### ISSUE TITLE
Axes don't detect wood that is 'indirectly' part of a tree

### ISSUE THREAD

**Issue by RoyalDister** [Levoment/SuperAxes#4] opened 2020-11-04 22:19 UTC
I have a mod that adds a large tree that has logs scattered throughout it, and the superaxes don't detect those logs, leaving a flying mass of leaves and interspersed logs. I'm not sure how or even *if* you can fix this, it's just inconvenient to have to find all of the remaining logs after cutting each tree.

**Comment by Levoment** [comment] 2020-11-15 22:30
Hi,

Thanks for opening an issue.

In the first few versions of the mod, those logs would have been detected and harvested because of the algorithm that was used to scan for logs. That algorithm however caused large areas of a forest to be chopped down and thereby lag, low FPS, and unresponsiveness. A pull request was created to fix the problem. Later, the algorithm changed as new bugs appeared and new features added.

The problem is that the game generates forests with trees that touch each other by leaves. If we scan for logs that are separated by leaves it will take all of those trees to harvest them. 

One solution to this issue in which wood that is indirectly part of a tree is not detected is to go back to the old algorithm which would make the mod lag the game, lower FPS, and make the game unresponsive. The other solution is to modify the current algorithm and add a configuration option which might be able to detect wood that is indirectly part of a tree depending on how the user configures it. That however may also cause lag, lower the game FPS, and cause the game to become unresponsive.

The latter was implemented. A warning was put as a tooltip on the configuration option to let the player know that it is not recommended to change the defaults of that option.

You can find the implementation on the mod version [2.0.7](https://github.com/Levoment/SuperAxes/releases/tag/refs%2Fheads%2Frelease%2F2.0.7)

That mod version is compatible only with the game versions 1.16.2 and 1.16.4.

To try it, one goes into the configuration menu of the mod or the configuration file and changes the **Scanning area shape scale** to a number that would increase the size of the original shape. Originally, the mod scans for logs in a 3x3x3 cube. Increasing the number will give a scan area whose range goes from the negative of the number to the positive of it. A number of 2 there would give an area of 5x5x5 since it goes from -2 to 2 on each axis. A number of 3 would give an area of 7x7x7. A number of 4 would give an area of 9x9x9 and so on. That area of scanning is applied to each and every log.

That will fix that problem, but the player must be aware that it can cause lag and unresponsiveness. Below is an example of what happens when the default scanning size is changed from the default. All the logs with a red outline are the logs that will be harvested if the log over which the scanning was initiated on is mined.

![Scan shape change](https://raw.githubusercontent.com/Levoment/SuperAxes/master/screenshots/Scan%20shape%20change.png)

**Comment by Levoment** [comment] 2020-11-15 22:32
Fixed by adding a configuration option to the mod on 

https://github.com/Levoment/SuperAxes/tree/ae8cbcae6edb4347ff50375f1682f9808b89d096

**Closed as completed by Levoment** 2020-11-15 22:32 UTC
